[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"


[too.pytest.ini_options]
addopts = "--cov=nitrado"
testpaths = [
    "tests",
]

[too.mypy]
mypy_path = "src"
